config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin, path: 'extranet' do
    resources :users do
      collection do
        get :new_invitation
        post :create_invitation
      end
    end
    resources :startups
    resources :job_offers
    resources :headlines
    resources :pages

    root to: "startups#index"
  end

  resources :startups
  resources :headlines
  resources :pages

  root to: "welcome#show"

  get ':id', to: 'pages#show', as: :extra_page
end

app/models/job_offer.rb
class JobOffer < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged finders history]

  belongs_to :startup

  has_rich_text :body

  validates :title, :body, :end_publishing_on, presence: true
end

app/models/legacy/job_offer.rb
class Legacy::JobOffer
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :body, type: String
  field :is_published, type: Boolean, default: true
  field :end_publishing_on, type: Date, default: 3.months.from_now.to_date

  belongs_to :startup

  scope :publicly_visible, -> { desc(:updated_at).where(is_published: true, end_publishing_on: {"$gt" => Time.now}) }

  validates :title, :body, :end_publishing_on, presence: true
end

app/controllers/admin/job_offers_controller.rb
class Admin::JobOffersController < Admin::BaseController

  inherit_resources

protected

  def permitted_params
    params.permit(job_offer: [:startup_id, :end_publishing_on, :is_published, :title, :body])
  end

  def begin_of_association_chain
    if current_user.is_admin?
      nil
    else
      @startup = current_user.startups.first
    end
  end

  def collection
    sort_param, sort_order = params[:s].present? ? params[:s].split("+") : [nil, nil]
    sort_param ||= :created_at
    sort_order ||= :desc
    hsh = {}
    hsh[sort_param.to_sym] = sort_order.to_sym
    get_collection_ivar || set_collection_ivar(end_of_association_chain.order(hsh))
  end

public

  def create
    create! do |success, failure|
      success.html {
        redirect_to({action: :index})
      }
    end
  end

  def update
    update! do |success, failure|
      success.html {
        redirect_to({action: :index})
      }
    end
  end
end

app/views/admin/job_offers/_form.html.haml
- @page_title = @job_offer.new_record? ? "Ajouter une nouvelle offre d'emploi" : "Modifier une offre d'emploi"
= simple_form_for [:admin, @job_offer] do |f|
  =# link_to 'Retour', {action: :index}, class: "btn btn-link"
  .row
    .col-12.col-md-8
      .form-group.bmd-form-group.bmd-form-group-lg
        = f.text_field :title, class: 'form-control form-control-lg', placeholder: 'Ajoutez un titre'
    .col-12.col-md-4
      = f.submit "Enregistrer", class: "btn btn-raised btn-primary "
  .row
    .col-12.col-md-8
      .form-group.bmd-form-group.bg-light
        = f.text_area :body, placeholder: 'Contenu', class: 'form-control'
    .col-12.col-md-4
      .checkbox.form-group.bmd-form-group
        %label
          = f.check_box :is_published
          %span.checkbox-decorator
            %span.check
          Publié ?
      %label.mb-2.mt-3 Date de fin de publication :
      .d-flex.flex-row.align-items-center.mb-3
        .form-group.bmd-form-group.bg-light.mb-0
          = f.date_field :end_publishing_on, class: 'form-control'
        .mx-2 à
        .form-group.bmd-form-group.bg-light.mb-0.d-flex.align-items-center
          = f.time_select :end_publishing_on, {}, class: 'bmd-form-group form-control pb-0'
      - if current_user.is_admin?
        %label.mb-2.mt-3 Startup concernée :
        = f.input :startup_id, collection: Startup.all, label: false, wrapper_html: {class: 'bg-light'}

app/views/admin/job_offers/edit.html.haml
= render partial: "form"

app/views/admin/job_offers/index.html.haml
.page-header
  %h1.page-header__title= @page_title = @startup.present? ? "Vos offres d'emploi" : "Toutes les offres d'emploi"
  = link_to new_admin_job_offer_path, class: "btn btn-raised btn-primary" do
    = fa_icon 'plus'
    Ajouter une offre d'emploi
- if @job_offers.any?
  %table.table.table-condensed.table-hover.table-striped
    %thead
      %tr
        %th.table-cell__column-title
          Nom
        %th= sort_link @q, :created_at, 'Ajouté'
        %th= sort_link @q, :end_publishing_on, 'Fin de publication'
        %th Publié ?
        %th
    %tbody
      - for job_offer in @job_offers
        %tr
          %td.table-cell__column-title
            = job_offer.title
          %td= I18n.l job_offer.created_at, format: :datetime
          %td= I18n.l job_offer.end_publishing_on, format: :added_on_short if job_offer.end_publishing_on.present?
          %td= job_offer.is_published? ? "oui" : "non"
          %td
            .actions
              =# link_to fa_icon('external-link-alt', title: 'Voir la fiche public'), job_offer, target: '_blank'
              = link_to fa_icon('edit', title: 'Modifier'), [:edit, :admin, job_offer]
              = link_to fa_icon('trash-alt', title: 'Supprimer'), [:admin,  job_offer], method: :delete, data: {confirm: 'Voulez-vous vraiment supprimer cette offre d\'empoi ?'}
- else
  %em{style: "display:block;margin-top:10px;"} Vous n'avez encore publié aucune annonce.

app/views/admin/job_offers/new.html.haml
= render partial: "form"