config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin, path: 'extranet' do
    resources :users do
      collection do
        get :new_invitation
        post :create_invitation
      end
    end
    resources :startups
    resources :job_offers
    resources :headlines
    resources :pages

    root to: "startups#index"
  end

  resources :startups
  resources :headlines
  resources :pages

  root to: "welcome#show"

  get ':id', to: 'pages#show', as: :extra_page
end

app/views/shared/_errors_and_notices.html.haml
- if flash[:error] || flash[:errors] || flash[:notice] || model.errors[:base].any?
  .row
    .col-xs-12
      - if flash[:error]
        .alert.alert-danger
          %strong!= flash[:error]

      - if model.errors[:base].any?
        .alert.alert-danger
          %strong= model.errors[:base].join(", ")

      - if flash[:errors]
        .alert.alert-danger
          %strong= flash[:errors]

      - if flash[:notice]
        .alert.alert-warning
          %strong= flash[:notice]

app/views/shared/_facebook_page_plugin.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=242612602426401";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_nav.html.haml
- extra_klass = controller.controller_name != 'welcome' && 'mb-5'
%nav.navbar.navbar-expand-lg{class: extra_klass}
  %button.navbar-toggler.p-0.border-0{type: :button, data: {toggle: 'offcanvas'}}
    %span.navbar-toggler-icon
  = link_to root_path, class: "navbar-brand" do
    = image_tag(asset_pack_path("media/images/logo.svg"))
  .collapse.navbar-collapse.offcanvas-collapse
    %ul.navbar-nav.ml-auto
      - extra_klass = controller.controller_name == 'headlines' && 'active'
      %li.nav-item{class: extra_klass}
        = link_to I18n.t("views.nav.headlines"), headlines_path, class: "nav-link"
      - extra_klass = controller.controller_name == 'startups' && 'active'
      %li.nav-item{class: extra_klass}
        = link_to I18n.t("views.nav.startups"), startups_path, class: "nav-link"
      - page_about = Page.where(code: "about").first
      - if page_about
        - extra_klass = @page && @page == page_about && 'active'
        %li.nav-item{class: extra_klass}
          = link_to page_about.title, extra_page_path(page_about), class: "nav-link"

%aside.offcanvas-collapse
  .drawer
    %ul.list-group
      - klass = %w(list-group-item)
      - klass << 'active' if controller.controller_name == 'headlines'
      = link_to I18n.t("views.nav.headlines"), headlines_path, class: klass
      - klass = %w(list-group-item)
      - klass << 'active' if controller.controller_name == 'startups'
      = link_to I18n.t("views.nav.startups"), startups_path, class: klass
      - page_about = Page.where(code: "about").first
      - if page_about
        - klass = %w(list-group-item)
        - klass << 'active' if @page && @page == page_about
        = link_to page_about.title, extra_page_path(page_about), class: klass

app/views/shared/_sidebar.html.haml
= link_to new_startup_path, class: "btn btn-info btn-block btn-raised mt-4" do
  = I18n.t("views.nav.startup_add")
- unless controller.controller_name == "welcome"
  - headline_focus = Headline.where(is_focus: true).desc(:published_at).first
  - headline_focus ||= Headline.desc(:published_at).first
  - if headline_focus
    %h3.mt-5.mb-3= t('.last_headline')
    = render partial: "headlines/card", locals: {headline: headline_focus, card_klass: ''}
.card.fb-page.mt-5{data: {href: "https://www.facebook.com/StrasbourgStartups", height: 500, tabs: "timeline", small: {header: "true"}, adapt: {container: {width: "true"}}, hide: {cover: "false"}, show: {facepile: "true"}}}
  %blockquote{cite: "https://www.facebook.com/StrasbourgStartups", class: "fb-xfbml-parse-ignore"}
    = link_to "French Tech Strasbourg", "https://www.facebook.com/StrasbourgStartups"

/ tweet wall