config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin, path: 'extranet' do
    resources :users do
      collection do
        get :new_invitation
        post :create_invitation
      end
    end
    resources :startups
    resources :job_offers
    resources :headlines
    resources :pages

    root to: "startups#index"
  end

  resources :startups
  resources :headlines
  resources :pages

  root to: "welcome#show"

  get ':id', to: 'pages#show', as: :extra_page
end

app/models/headline.rb
class Headline < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  extend FriendlyId
  friendly_id :title, use: %i[slugged finders history]

  has_rich_text :body

  has_one_attached :banner
  # validates_attachment_content_type :banner, content_type: /\Aimage/

  scope :publicly_visible, -> { order(published_at: :desc).where("published_at < ?", Time.now) }

  validates :title, :body, presence: true

  def chapo
    first_part = body.to_plain_text.split(/\.|\!|\?/).first
    first_part.present? ? (first_part.strip + ".").truncate(120) : nil
  end
end

app/models/legacy/headline.rb
class Legacy::Headline
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include Mongoid::Slug
  include Taggable

  store_in collection: 'headlines'

  field :title, type: String, localize: true
  field :body, type: String, localize: true
  field :published_at, type: Time, default: -> { Time.now }
  field :is_focus, type: Boolean, default: false

  validates :title, :body, presence: true

  # slug :title, history: true, localize: true
  slug :title, localize: true

  has_mongoid_attached_file :banner,
    styles: {
      small: ['100x100>', :png],
      medium: ['500x250#', :png]
    }
  validates_attachment_content_type :banner, content_type: /\Aimage/

  scope :publicly_visible, -> { desc(:published_at).where(published_at: {"$lt" => Time.now}) }

  def chapo
    first_part = ActionView::Base.full_sanitizer.sanitize(body).split(/\.|\!|\?/).first
    first_part.present? ? (first_part.strip + ".").truncate(120) : nil
  end
end

app/controllers/admin/headlines_controller.rb
class Admin::HeadlinesController < Admin::BaseController

  inherit_resources

protected

  def permitted_params
    params.permit(headline: [:published_at, :banner, :is_focus, :tag_list, :title, :body])
  end

  def collection
    get_collection_ivar || set_collection_ivar(end_of_association_chain.order(published_at: :desc).paginate(per_page: 20, page: params[:page]))
  end

public

  def create
    create! do |success, failure|
      success.html {
        redirect_to({action: :index})
      }
    end
  end

  def update
    update! do |success, failure|
      success.html {
        redirect_to({action: :index})
      }
    end
  end
end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController

  def index
    @headlines = Headline.publicly_visible
    if params[:tag].present?
      @headlines = @headlines.in(tags: params[:tag])
    end
    @headlines = @headlines.paginate per_page: 10, page: params[:page]
  end

  def show
    @headline = Headline.find params[:id]
  end
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
end

app/views/headlines/_card.html.haml
- card_klass ||= 'mt-3'
.card.headline{class: card_klass}
  = link_to headline do
    - if headline.banner.attached?
      - img = headline.banner.variable? ? headline.banner.variant(resize_to_limit: [500, 250]) : headline.banner
      = image_tag(img, style: 'width:100%;background-position: center center;background-size: cover;', class: 'card-img-top')
  .card-body
    %h1.h5.card-title= link_to headline.title, headline
    .card-text
      %small.text-muted.d-block.mt-0.mb-1
        = l(headline.published_at, format: :published_at, link: headline_path(headline)).html_safe
      - if headline.tags.any?
        %small.text-muted.d-block.my-2
          = headline.tags.map{|tag| link_to "##{tag}", headlines_path(tag: tag)}.join(" ").html_safe
    .card-text
      = strip_tags(headline.chapo)
  .card-footer
    = link_to t("views.welcome.show.read_more"), headline, class: "btn btn-primary"

app/views/headlines/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '<%= ENV["DISQUS_SHORTNAME"] %>'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/headlines/_headline.html.haml
.row.mt-5.headline
  .col-12
    = link_to headline do
      .h2= headline.title
    %small.text-muted.d-block
      = strip_tags(l(headline.published_at, format: :published_at))
    - if headline.tags.any?
      %small.text-muted.d-block
        = headline.tags[I18n.locale].map{|tag| link_to "##{tag}", headlines_path(tag: tag)}.join(" ").html_safe
    - if headline.banner.file?
      = link_to headline do
        = image_tag(headline.banner.url(:medium), class: "img-fluid my-5 d-block")
    = strip_tags(headline.chapo)
    .d-block
      = link_to t("views.welcome.show.read_more"), headline, class: "btn btn-transparent mt-2"
.row
  .col-12
    %hr

app/views/headlines/index.html.haml
- @page_title = t("views.headlines.index.page_title")
%section
  .container
    .row
      .col-12
        %h1= @page_title = t("views.headlines.index.page_title")
    .row
      .col-12
        .card-deck.headlines-list
          = render partial: "headlines/card", collection: @headlines, as: :headline, locals: {card_klass: 'mt-4'}

        = will_paginate @headlines, list_classes: %w(pagination justify-content-center mt-5 flex-wrap)

app/views/headlines/show.html.haml
- @page_title = @headline.title
- @og_image = url_for(@headline.banner) if @headline.banner.attached?
.container
  .row
    .col-12.col-md-8.mx-md-auto.col-lg-9
      .row
        .col-12
          = link_to headlines_path, class: "btn" do
            = fa_icon "angle-left"
            &nbsp;
            = t("views.common.return_headlines_list")
      .row
        .col-12
          .text-muted.mt-3.mb-0
            = strip_tags(l(@headline.published_at, format: :published_at))
          %h1.display-4.mt-0{class: @headline.tags.any? ? 'mb-2' : 'mb-3'}
            = @headline.title
          - if @headline.tags.any?
            %small.text-muted.d-block.mb-3
              = @headline.tags.map{|tag| link_to "##{tag}", headlines_path(tag: tag)}.join(" ").html_safe
          - if @headline.banner.attached?
            - img = @headline.banner.variable? ? @headline.banner.variant(resize_to_limit: [500, 250]) : @headline.banner
            = image_tag(img, class: "img-fluid", style: "margin:20px 0;")
          = @headline.body
      .row
        .col-12
          = render partial: "disqus"